blank_issues_enabled: true
contact_links:
  - name: mingyeong's github
    url: https://github.com/mingyeong0210
    about: mingyeong's github
  - name: devcourse study github
    url: https://github.com/mingyeong0210/ProgrammersDevCourse
    about: devcourse study github
